trigger:
  branches:
    include:
      - master
      - azure-pipelines

jobs:
  - job: BrowserTests
    displayName: 'Run Tests'
    strategy:
      matrix:
        Chrome:
          browser: CHROME
        Edge:
          browser: EDGE
        Firefox:
          browser: FIREFOX
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Maven@3
        displayName: 'Run Tests on $(browser)'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.21'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'test'
          options: '-Dbrowser=$(browser) --batch-mode --fail-at-end'