trigger:
  branches:
    include:
      - master
      - azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  displayName: 'Run Tests on Chrome'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
    options: '-Dbrowser=CHROME --batch-mode --fail-at-end'

- task: Maven@3
  displayName: 'Run Tests on Edge'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
    options: '-Dbrowser=EDGE --batch-mode --fail-at-end'

- task: Maven@3
  displayName: 'Run Tests on Firefox'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
    options: '-Dbrowser=FIREFOX --batch-mode --fail-at-end'