name: Java CI with Maven (Cross-Browser)

on:
  push:
    branches: [ "master", "Cross-browser-setup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Run Tests on ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [CHROME, FIREFOX, EDGE]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Edge
      if: matrix.browser == 'EDGE'
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/
        sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
        sudo apt update
        sudo apt install -y microsoft-edge-stable
        rm microsoft.gpg

    - name: Build and Run Tests
      run: mvn test -Dbrowser=${{ matrix.browser }} --batch-mode --fail-at-end

    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1