name: Java CI with Maven (Cross-Browser)

on:
  push:
    branches: [ "master", "Cross-browser-setup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Run Tests on ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [CHROME, EDGE, FIREFOX]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run Tests
        run: mvn test -Dbrowser=${{ matrix.browser }} --batch-mode --fail-at-end

      - name: Publish Test Report (${{ matrix.browser }})
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/surefire-reports/TEST-*.xml'
          check_name: "Test Report - ${{ matrix.browser }}"